### ISSUE TITLE
Strange Syntax?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-3-python-variable-scope#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/variable-scope?module_item_id=439010

### Concern

In the last example of the **Function Scope in Python** section, we write `im_trapped_in_a_function( )`, as if it were a function, when it's been declared as a variable in the `practicing_function_scope` function. We'll get the appropriate error regardless, but why does it have parentheses here? No stress if there's a valid reason - I just may not be aware of it.

**Comment by professor-ben** [comment]
Great catch- calling an undefined class or function returns a NameError, but using an undefined variable name outside of a call returns a very unhelpful SyntaxError. Pushing up the fix in a moment.
